#! /usr/bin/env bash
set -x
src_absfn_str=$(realpath $1)
src_basename_str=$(basename $src_absfn_str)
projname_str=$(echo $src_basename_str | sed 's/\.rs//g')
tmpabsdn_str=$(mktemp -d -t rustrun_XXXXXXXXXXX)
#echo $tmpabsdn_str
#/data/data/com.termux/files/usr/tmp/runnerCy794qsVcqb
# last test: rustrun_2Tv6am3YMI7
projtmpabsdn_str=$tmpabsdn_str
pushd $tmpabsdn_str
cargo new $projname_str
projtmpabsdn_str=$tmpabsdn_str/$projname_str
echo -e "\n[profile.dev]\nincremental = false" >> $projtmpabsdn_str/Cargo.toml
cat $src_absfn_str | sed 's/^#!.*$//g' > $projtmpabsdn_str/src/main.rs

cd $projtmpabsdn_str
cargo run