#! /usr/bin/env bash
src_fn_str=$1
proj_name_str=$(echo $src_fn_str | sed -r 's/([^\.]+)\.rs/\1/g')
tmp_dn_str=$(mktemp -d -t runnerXXXXXXXXXX)
#echo "@ps rustrun run as '$0 $1 $2 $3'"
#echo "src exe $src_fn_str $bin_fn_str"

target_fn_with_dir_str=$bin_dir/bin_fn_str
rustc $src_fn_str -o $target_fn_with_dir_str && (./$($fn_with_dir_str  && rm $fn_with_dir_str) || echo "Errors while compile or exec. Please check and fix errors above"
echo "Cleaning up $bin_dir"
rm -rf $bin_dir