#! /usr/bin/env bash
src_absfn_str=$(realpath "$1")
src_basename_str=$(basename "$src_absfn_str")
projname_str=$(echo "$src_basename_str" | sed 's/\.rs//g')
tmpabsdn_str=$(mktemp -d -t rustrun_XXXXXXXXXXX)
projtmpabsdn_str=$tmpabsdn_str
pushd $tmpabsdn_str
cargo new $projname_str
cn_ec_int=$?
if [ $cn_ec_int -ne 0 ]; then
	echo -e "\x1b[91mFailed to create project $projname_str in $tmpabsdn_str Please fix error(s) above and then re-run.\x1b[0m"
	exit $cn_ec_int
fi
projtmpabsdn_str=$tmpabsdn_str/$projname_str
echo -e "\n[profile.dev]\nincremental = false" >> "$projtmpabsdn_str/Cargo.toml"
cat "$src_absfn_str" | sed 's/^#!.*$//g' > "$projtmpabsdn_str/src/main.rs"


cd "$projtmpabsdn_str" || exit 1
cargo run && echo -e "\x1b[92mProgram finished succesfully with exit code $?\x1b[0m" || echo -e "\x1b[91mProgram finished with errors. Exit code is $?\x1b[0m"