#! /usr/bin/env bash
set -x
params_str=$1
srcsqlfn_str=$2
#echo "@ps in sqliterun with params 0:$0 1:$1 2:$2 3:$3 4:$4 5:$5"
#exit 0



dbfn_str=$(sqliterun_getdbpath.py $params_str)
echo "Path to db is $dbfn_str"